# # Do not modify this file!  It was generated by ‘nixos-generate-config’
# # and may be overwritten by future invocations.  Please make changes
# # to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
#   hardware.enableRedistributableFirmware = true;

#   boot.initrd.availableKernelModules =
#     [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
#   boot.initrd.kernelModules = [ "dm-snapshot" ];
#   boot.kernelModules = [ "kvm-intel" ];
#   boot.extraModulePackages = [ ];

#   boot.initrd.luks = {
#     fido2Support = true;
#     devices = {
#       cryptlvm = {
#         device = "/dev/disk/by-uuid/f7bc178e-d0b6-4834-b70d-4ef806ebcb85";
#         preLVM = true;
#         fido2 = {
#           credential = "ff36a96f08cb13015ab38162fcd11276b8154ac3454c2d1d198cec3d2e9eb1f888c652dae2262619c1da2be7562ec9dd94888c71a9326fea70dfe16214b5ea8ec01463080000";
#           gracePeriod = 15;
#           passwordLess = true;
#         };
#       };
#     };
#   };


#   fileSystems."/" =
#     { device = "/dev/mapper/vg0-lv--root";
#       fsType = "btrfs";
#     };

#   fileSystems."/boot" =
#     { device = "/dev/disk/by-uuid/B83A-1E85";
#       fsType = "vfat";
#     };

#   fileSystems."/home" =
#     { device = "/dev/mapper/vg0-lv--home";
#       fsType = "btrfs";
#     };

#   swapDevices =
#     [ { device = "/dev/mapper/vg0-lv--swap"; }
#     ];

#   nix.maxJobs = lib.mkDefault 8;
#   powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
#   # High-DPI console
#   console.font =
#     lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
