#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### theme #####
PALETTE_BASE="0x11111b24"
PALETTE_TEXT="0xffe0def4"
PALETTE_MALVE="0xffc4a7e7"
PALETTE_GREEN="0xff9ccfd8"
PALETTE_BLUE="0xff31748f"
PALETTE_YELLOW="0xfff6c177"
#################


default=(
  padding_left=5
  padding_right=5
  icon.font="BlexMono Nerd Font Mono:Bold:15.0"
  label.font="Inter:Semibold:15.0"
  # icon.color=0xdd1e1e2e   # Dark
  # label.color=0xdd1e1e2e
  icon.color="$PALETTE_TEXT"     # Light
  label.color="$PALETTE_TEXT"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

bar=(
  height=33
  color="$PALETTE_BASE"
)
sketchybar --bar "${bar[@]}"

no_margin=(
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=0
  label.padding_right=0
)



sketchybar --add item front_app q \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding AeroSpace Indicators #####

sketchybar --default "default[@]"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add event change_keyboard_layout

sketchybar --default icon.font.size=20

sketchybar --add item clock right \
           --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
           --add item keyboard right \
           --set keyboard icon="" script="$PLUGIN_DIR/keyboard.sh" \
           --subscribe keyboard change_keyboard_layout \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" icon.font.size=17 \
           --set volume icon.color="$PALETTE_BLUE" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" icon.font.size=17 \
           --set battery icon.color="$PALETTE_YELLOW" \
           --subscribe battery system_woke

cpu=(
 update_freq=2
 "${no_margin[@]}"
 icon.padding_right=5
 icon=""
 icon.color="$PALETTE_MALVE"
 script="$PLUGIN_DIR/cpu.sh"
)

sketchybar --add item cpu right \
           --set cpu "${cpu[@]}"

mem=(
 update_freq=2
 "${no_margin[@]}"
 icon.padding_right=5
 icon=""
 icon.color="$PALETTE_GREEN"
 script="$PLUGIN_DIR/memory.sh"
)

sketchybar --add item memory right \
           --set memory "${mem[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
