groups:
- name: ssl_expiry.rules
  rules:
  - alert: SSLCertExpiringSoon
    expr: probe_ssl_earliest_cert_expiry{job="blackbox"} - time() < 86400 * 30
    for: 10m
    annotations:
      summary: 'SSL expire alert'
      description: "SSL certificate for the {% raw %}{{ $labels.instance }}{% endraw %} will expire soon!"
