_: {
  imports = [
    ./autobrowser.nix
    ./alacritty.nix
    ./cliphist.nix
    ./direnv.nix
    ./firefox.nix
    ./ghostty.nix
    ./git.nix
    ./go.nix
    ./gpg-agent.nix
    ./home-packages.nix
    ./hyprland
    ./index.nix
    ./java.nix
    ./keyring.nix
    ./nh.nix
    ./npm.nix
    ./nvim
    ./portals.nix
    ./python.nix
    ./rofi
    ./services.nix
    ./shell.nix
    ./ssh-agent.nix
    ./stylix.nix
    ./swaync.nix
    ./swayosd.nix
    ./taskwarrion.nix
    ./theme.nix
    ./vscode.nix
    ./waybar
    ./xdg.nix
    ./zed.nix
    ./spotify.nix
  ];
}
