# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/profiles/qemu-guest.nix")];

  boot = {
    initrd = {
      availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];
      kernelModules = [];
    };
    kernelModules = [];
    extraModulePackages = [];

    kernel.sysctl."net.ipv4.ip_forward" = 1;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7707dfcc-43b0-471a-9041-dcd8b9bf97aa";
    fsType = "ext4";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/c286e8a7-fc51-4344-9c8d-be7c3661b3a5";}];

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
