# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}: let
  consts = import ../constants.nix;
in {
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot" "dm-mirror"];
  boot.kernelModules = ["kvm-amd"];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/a752d8ed-a692-447b-b1f2-92baa9c2300a";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/C0F8-3889";
      fsType = "vfat";
    };

    "${consts.archiveMountPoint}" = {
      device = "/dev/vg01/archive";
      fsType = "ext4";
    };

    "${consts.storeMountPoint}" = {
      device = "/dev/vg02/publicstore";
      fsType = "ext4";
    };
  };

  swapDevices = [{device = "/dev/disk/by-uuid/f7e254a9-e6b9-4b1e-a238-af7778b9f7a2";}];

  nix.settings.max-jobs = lib.mkDefault 8;

  hardware.enableRedistributableFirmware = true;
  # hardware.opengl.driSupport32Bit = true;
  hardware.opengl.enable = true;
}
