# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];

  boot.kernelParams = [
    "i2c.timeout=100"
    "drm.debug=0"
    "nvidia.NVreg_TemporaryFilePath=/var/tmp"
  ];
  boot.blacklistedKernelModules = [ "i2c_designware_pci" "i2c_designware_platform" ];

  boot.initrd.luks.devices."lvm".device = "/dev/nvme0n1p2";
  boot.loader.systemd-boot.consoleMode = "max";

  boot.kernelModules = ["kvm-intel" "hp-wmi"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/vg0-root";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CE93-2BAE";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/vg0-root";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime"];
  };

  swapDevices = [
    {device = "/dev/mapper/vg0-swap";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
